version: "3"
services:
  #  Create a service named db.
  db:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "my_postgres"
    volumes:
      - "../db-data:/docker-entrypoint-initdb.d/"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      POSTGRES_URL: postgres://postgres:babaka11@db:5432/greenFieldProducts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: babaka11
      POSTGRES_DB: greenFieldProducts
    ports:
    - "5432:5432"
    restart: on-failure
    #   Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.

    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    links:
      - db
    depends_on:
      - db
    ports:
    - "80:8080"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5