config:
  target: "http://localhost:3000"
  phases:
    - duration: 10
      arrivalRate: 200
  payload:
    path: "../../db-data/product.csv"
    fields:
      - "id"
    skipHeader: true
scenarios:
  - flow:
      - get:
          url: "/products/{{ id }}/styles"
